<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>fsh</string>
    <key>scopeName</key>
    <string>source.fsh</string>
    <key>fileTypes</key>
    <array>
      <string>fsh</string>
    </array>
  <key>uuid</key>
  <string>1E4DD6BF-567F-434F-B3FA-3D8276267A3D</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#urls</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#booleans</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#numbers</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#codes</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.fsh</string>
            <key>match</key>
            <string>\b(Alias|Characteristics|Expression|Description|Mixins|Severity|Target|Title|Usage|XPath)(?=\s*:)\b</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(Context)\s?(:)\s+</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.tokens.fsh</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(("(?:\\.|[^\\"])*")|([^"\s][^\s,]+))\s+(?!,)</string>
            <key>endCaptures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>string.quoted.double.fsh</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.quoted.double.fsh</string>
                <key>begin</key>
                <string>"</string>
                <key>end</key>
                <string>"\s*(,)\s*</string>
                <key>endCaptures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.tokens.fsh</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>constant.character.escape.fsh</string>
                    <key>match</key>
                    <string>\.</string>
                  </dict>
                </array>
              </dict>
              <dict>
                <key>match</key>
                <string>([^\s,]+)\s*(,)\s*</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsh</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.tokens.fsh</string>
                  </dict>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(CodeSystem|Extension|Id|Instance|InstanceOf|Invariant|Logical|Mapping|Parent|Profile|Resource|RuleSet|Source|ValueSet)\s?(:)\s+([A-Za-z0-9_.:$/-]+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.control.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.tokens.fsh</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.reserved.fsh</string>
            <key>match</key>
            <string>\b(?&lt;=\s|^)(and|codes|contains|descendent-of|exclude|exists|generalizes|include|in|is-a|is-not-a|named|not-in|or|regex|(?&gt;\bfrom\s*)system|units|valueset|where|D|MS|N|SU|TU|\?!)(?=\s)\b</string>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;=\s|^)(from|obeys)\s+(\S+)((\s+and\s+(\S+))*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
              <key>3</key>
              <dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>name</key>
                    <string>keyword.reserved.fsh</string>
                    <key>match</key>
                    <string>(and)</string>
                  </dict>
                  <dict>
                    <key>name</key>
                    <string>entity.name.type.fsh</string>
                    <key>match</key>
                    <string>\S+</string>
                  </dict>
                </array>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(?&lt;=\s|^)(only)\s+([A-Za-z0-9_-]+\b(?!\())?</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(insert)\s+(\S*?)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;!\\)\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>string.quoted.other.bracketed.fsh</string>
                <key>begin</key>
                <string>(?&lt;=[^\\][,\(]\s*)\[\[</string>
                <key>end</key>
                <string>\]\](?=\s*[,)])</string>
              </dict>
              <dict>
                <key>name</key>
                <string>variable.parameter.fsh</string>
                <key>match</key>
                <string>([^\s\),]+)</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>match</key>
            <string>\b(insert)\s+(\S+)\b</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.reserved.fsh</string>
            <key>match</key>
            <string>(\(\s*)(exactly|example|extensible|preferred|required)(\s*\))</string>
          </dict>
          <dict>
            <key>begin</key>
            <string>\b(Reference|Canonical|CodeableReference)\s*\(</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>keyword.reserved.fsh</string>
                <key>match</key>
                <string>(or)</string>
              </dict>
              <dict>
                <key>name</key>
                <string>entity.name.type.fsh</string>
                <key>match</key>
                <string>([^\s\)]+)</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.tokens.fsh</string>
            <key>match</key>
            <string>((?&lt;!\.)\*)|-&gt;|=|\+|:</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>name</key>
        <string>string.quoted.double.fsh</string>
        <key>begin</key>
        <string>"</string>
        <key>end</key>
        <string>"</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fsh</string>
            <key>match</key>
            <string>\\.</string>
          </dict>
        </array>
      </dict>
      <key>urls</key>
      <dict>
        <key>name</key>
        <string>url.fsh</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&amp;\/\/=]*))\b</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>string.unquoted.url.fsh</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>booleans</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.fsh</string>
            <key>match</key>
            <string>\b(?&lt;=\s|^)(true|false)(?=\s)\b</string>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.fsh</string>
            <key>match</key>
            <string>\b(?&lt;=[\s,]|^)(-?\d+(\.\d+)?)(?=[\s,])\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.fsh</string>
            <key>match</key>
            <string>\b(\d*\.\.(\d+|\*)?)\b</string>
          </dict>
        </array>
      </dict>
      <key>codes</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.quoted.code.fsh</string>
            <key>match</key>
            <string>#"(?:\\.|[^\\"])*"</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.code.fsh</string>
            <key>match</key>
            <string>#[^\s,]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.ucum.unit.fsh</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.code.fsh</string>
            <key>match</key>
            <string>\$[^\s]*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.character.escape.fsh</string>
            <key>match</key>
            <string>(\^\S+)</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>name</key>
        <string>comment.fsh</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>(\s|^)//</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.fsh</string>
              </dict>
            </dict>
            <key>end</key>
            <string>$</string>
            <key>name</key>
            <string>comment.line.double-slash.fsh</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.fsh</string>
            <key>begin</key>
            <string>/\*</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.fsh</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.fsh</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
